### ISSUE TITLE
[Bug Report] `vue add vuetify` not working

### ISSUE THREAD

**Issue by Antonito** [vuetifyjs/vue-cli-plugins#151]
- MacOS 10.15.2
- node v13.5.0
- npm 6.13.4
- @vue/cli 4.1.2

For `package.json`:
```
    "vuetify": "^2.1.0"
    "vue-cli-plugin-vuetify": "^2.0.3",
    "vuetify-loader": "^1.3.0",
```

➜ `vue init webpack .` (default on every option)
➜ `vue add vuetify`
```
📦  Installing vue-cli-plugin-vuetify...

+ vue-cli-plugin-vuetify@2.0.3
removed 26 packages and updated 1 package in 6.918s

23 packages are looking for funding
  run `npm fund` for details

✔  Successfully installed plugin: vue-cli-plugin-vuetify

? Choose a preset: Default (recommended)

🚀  Invoking generator for vue-cli-plugin-vuetify...
📦  Installing additional dependencies...

added 26 packages from 33 contributors in 12.673s

26 packages are looking for funding
  run `npm fund` for details

⠋  Running completion hooks... ERROR  Error: ENOENT: no such file or directory, open '/.../project/public/index.html'
Error: ENOENT: no such file or directory, open '/.../project/public/index.html'
    at Object.openSync (fs.js:456:3)
    at Object.writeFileSync (fs.js:1297:35)
    at Object.updateFile (/.../project/node_modules/vue-cli-plugin-vuetify/generator/tools/helpers.js:43:6)
    at Object.addLinks (/.../project/node_modules/vue-cli-plugin-vuetify/generator/tools/fonts.js:55:11)
    at /.../project/node_modules/vue-cli-plugin-vuetify/generator/index.js:36:35
    at runGenerator (/usr/local/lib/node_modules/@vue/cli/lib/invoke.js:145:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async invoke (/usr/local/lib/node_modules/@vue/cli/lib/invoke.js:105:3)
```

➜ `npm run dev`
```

> project@1.0.0 dev /.../project
> webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

 ERROR  Failed to compile with 118 errors10:59:23 PM

 error  in ./node_modules/vuetify/src/directives/ripple/VRipple.sass

Module build failed: ValidationError: Invalid options object. Sass Loader has been initialised using an options object that does not match the API schema.
 - options has an unknown property 'indentedSyntax'. These properties are valid:
   object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter? }
    at validate (/.../project/node_modules/sass-loader/node_modules/schema-utils/dist/validate.js:85:11)
    at Object.loader (/.../project/node_modules/sass-loader/dist/index.js:36:28)

 @ ./node_modules/vuetify/src/directives/ripple/VRipple.sass 4:14-179 13:3-17:5 14:22-187
 @ ./node_modules/vuetify/lib/directives/ripple/index.js
 @ ./node_modules/vuetify/lib/directives/index.js
 @ ./node_modules/vuetify/lib/index.js
 @ ./src/plugins/vuetify.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

 error  in ./node_modules/vuetify/src/components/VCalendar/VCalendarWeekly.sass

(...)

Module parse failed: Unexpected token (103:41)
You may need an appropriate loader to handle this file type.
|       if (this.showSelect) {
|         const index = headers.findIndex(h => h.value === 'data-table-select');
|         if (index < 0) headers.unshift({ ...defaultHeader,
|           value: 'data-table-select'
|         });else headers.splice(index, 1, { ...defaultHeader,

 @ ./node_modules/vuetify/lib/components/VDataTable/index.js 2:0-38
 @ ./node_modules/vuetify/lib/components/index.js
 @ ./node_modules/vuetify/lib/index.js
 @ ./src/plugins/vuetify.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

 error  in ./node_modules/vuetify/lib/components/VSelect/VSelect.js

(...)
```

**Comment by RobinSuvendo** [comment]
@Antonito & rest
did someone found a way to install vuetify on a new vue project via cli?

**Comment by KaelWD** [comment]
> `vue init webpack .`

This is the legacy vue-cli 2 templates, you can't use vue-cli 3 plugins with them. To install vuetify on a project created with `vue init` you need to follow the [instructions for webpack](https://vuetifyjs.com/en/getting-started/installation/#webpack-install)
