### ISSUE TITLE
[Bug Report] TypeError: Received an unexpected value [object Undefined]

### ISSUE THREAD

**Issue by cyluxx** [vuetifyjs/vue-cli-plugins#169]
### Environment

**Browsers:** Chromium 80.0.3987.87
**OS:** Linux

### Steps to reproduce
- Create new vue project
- `vue add vuetify`
- _Successfully installed plugin_
- Choose a preset -> Default (recommended)

### Expected Behavior
Vue Cli Plugin configures project

### Actual Behavior
```
Invoking generator for vue-cli-plugin-vuetify...
 ERROR  TypeError: Received an unexpected value [object Undefined]
TypeError: Received an unexpected value [object Undefined]
    at fromAST (/usr/lib/node_modules/@vue/cli/node_modules/jscodeshift/src/core.js:70:9)
    at core (/usr/lib/node_modules/@vue/cli/node_modules/jscodeshift/src/core.js:45:5)
    at newCore (/usr/lib/node_modules/@vue/cli/node_modules/jscodeshift/src/core.js:142:12)
    at toPropertyHash (/usr/lib/node_modules/@vue/cli/lib/util/codemods/injectOptions.js:19:49)
    at Array.map (<anonymous>)
    at injectOptions (/usr/lib/node_modules/@vue/cli/lib/util/codemods/injectOptions.js:20:42)
    at newTransform (/usr/lib/node_modules/@vue/cli/node_modules/vue-jscodeshift-adapter/src/jscodeshift-mode.js:9:14)
    at runCodemod (/usr/lib/node_modules/@vue/cli/lib/util/runCodemod.js:29:26)
    at /usr/lib/node_modules/@vue/cli/lib/Generator.js:290:23
    at Array.forEach (<anonymous>)
```

### Reproduction Link
<a href="" target="_blank"></a>

**Comment by onurusluca** [comment]
Having this too. Any solutions?

**Comment by ElijahKotyluk** [comment]
This will be resolved in next release.

**Comment by baojie223** [comment]
still not resolved

**Comment by cplpearce** [comment]
I'm having this same issue with `vue add router`
