### ISSUE TITLE
'vue add vuetify' fails

### ISSUE THREAD

**Issue by fredaas** [vuetifyjs/vue-cli-plugins#175]
Installing Vuetify with said command fails with the following error message:

```
ERROR  Error: did not recognize object of type "ImportExpression"
Error: did not recognize object of type "ImportExpression"
    at Object.getFieldNames (/usr/local/lib/node_modules/@vue/cli/node_modules/jscodeshift/node_modules/ast-types/lib/types.js:701:19)
    at visitChildren (/usr/local/lib/node_modules/@vue/cli/node_modules/jscodeshift/node_modules/ast-types/lib/path-visitor.js:223:36)
    at Visitor.PVp.visitWithoutReset (/usr/local/lib/node_modules/@vue/cli/node_modules/jscodeshift/node_modules/ast-types/lib/path-visitor.js:204:20)
    at visitChildren (/usr/local/lib/node_modules/@vue/cli/node_modules/jscodeshift/node_modules/ast-types/lib/path-visitor.js:246:25)
    at Visitor.PVp.visitWithoutReset (/usr/local/lib/node_modules/@vue/cli/node_modules/jscodeshift/node_modules/ast-types/lib/path-visitor.js:204:20)
    at visitChildren (/usr/local/lib/node_modules/@vue/cli/node_modules/jscodeshift/node_modules/ast-types/lib/path-visitor.js:246:25)
    at Visitor.PVp.visitWithoutReset (/usr/local/lib/node_modules/@vue/cli/node_modules/jscodeshift/node_modules/ast-types/lib/path-visitor.js:204:20)
    at NodePath.each (/usr/local/lib/node_modules/@vue/cli/node_modules/jscodeshift/node_modules/ast-types/lib/path.js:101:26)
    at visitChildren (/usr/local/lib/node_modules/@vue/cli/node_modules/jscodeshift/node_modules/ast-types/lib/path-visitor.js:219:18)
    at Visitor.PVp.visitWithoutReset (/usr/local/lib/node_modules/@vue/cli/node_modules/jscodeshift/node_modules/ast-types/lib/path-visitor.js:204:20)
```

Relevant packages installed:

```
"vue": "^2.6.11"
"vuetify-loader": "^1.4.3"
"vue-cli-plugin-vuetify": "^2.0.5"
```

Any help to solve this is much appreciated.

Edit:

System: Linux 4.15.0-72-generic, Ubuntu 18.04.3 LTS

**Comment by fredaas** [comment]
The problem was circumvented by installing Vuetfiy through npm instead. I.e.

```
npm install vuetify
```

and

```
npm install sass node-sass sass-loader deepmerge fibers -D
```

Closing.

**Comment by Sceat** [comment]
@fredaas what is the point of having a vue cli plugin if the issue is closed with the solution of not using the plugin ?

mine fails with `Error: did not recognize object of type "ChainExpression"`

**Comment by y-a-ava** [comment]
hi @Sceat, @fredaas
it looks to be vue-cli issue.
i upgraded from 4.5.6 to 4.5.13 and this error is gone now.
give it a try.
