### ISSUE TITLE
[Bug report] Vuetify fails with vue 3. 

### ISSUE THREAD

**Issue by zfxstd** [vuetifyjs/vue-cli-plugins#209]
Vue CLI 4.5.7
vue-cli-plugin-vuetify@2.0.7

Steps to reproduce: 

> vue create vue
** select "Default (Vue 3 Preview) ([Vue 3] babel, eslint)"
> cd vue
> vue add vuetify
** select "Default (recommended)"

```
ERROR  Error: You cannot call "get" on a collection with no paths. Instead, check the "length" property first to verify at least 1 path exists.            
Error: You cannot call "get" on a collection with no paths. Instead, check the "length" property first to verify at least 1 path exists.                    
    at Collection.get (C:\Users\noname\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\jscodeshift\src\Collection.js:213:13)                         
    at injectOptions (C:\Users\noname\AppData\Roaming\npm\node_modules\@vue\cli\lib\util\codemods\injectOptions.js:15:6)                                    
    at runTransformation (C:\Users\noname\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\vue-codemod\dist\src\run-transformation.js:61:17)          
    at C:\Users\noname\AppData\Roaming\npm\node_modules\@vue\cli\lib\Generator.js:290:23                                                                    
    at Array.forEach (<anonymous>)                                                                                                                          
    at Generator.resolveFiles (C:\Users\noname\AppData\Roaming\npm\node_modules\@vue\cli\lib\Generator.js:276:24)                                           
    at processTicksAndRejections (internal/process/task_queues.js:89:5)                                                                                     
    at async Generator.generate (C:\Users\noname\AppData\Roaming\npm\node_modules\@vue\cli\lib\Generator.js:175:5)                                          
    at async runGenerator (C:\Users\noname\AppData\Roaming\npm\node_modules\@vue\cli\lib\invoke.js:111:3)                                                   
    at async invoke (C:\Users\noname\AppData\Roaming\npm\node_modules\@vue\cli\lib\invoke.js:92:3)                                                          
```

**Comment by zfxstd** [comment]
Sorry, didnt saw the roadmap.
