### ISSUE TITLE
[Bug Report] Support for TypeScript

### ISSUE THREAD

**Issue by Glosur** [vuetifyjs/vue-cli-plugins#245]
### Environment

**Browsers:** Chrome 87.0.4280.141
**OS:** Linux x86_64

### Steps to reproduce
Try to add vuetify 3 to a Typescript project

### Expected Behavior

I have no error

### Actual Behavior

There is a missing template file, as shown is following error

```
🚀  Invoking generator for vue-cli-plugin-vuetify...
 ERROR  Error: ENOENT: no such file or directory, stat '[...]/node_modules/vue-cli-plugin-vuetify/generator/templates/v3/src/components/HelloWorld.ts.vue'
Error: ENOENT: no such file or directory, stat '[...]/node_modules/vue-cli-plugin-vuetify/generator/templates/v3/src/components/HelloWorld.ts.vue'


<!-- generated by vuetify-issue-helper. DO NOT REMOVE -->

**Comment by lorindabakken** [comment]
same

` ERROR  Error: ENOENT: no such file or directory, stat '/Users/bakken/Documents/projects/repos/mydashboard-client/node_modules/vue-cli-plugin-vuetify/generator/templates/v3/src/App.ts.vue'
Error: ENOENT: no such file or directory, stat '/Users/bakken/Documents/projects/repos/mydashboard-client/node_modules/vue-cli-plugin-vuetify/generator/templates/v3/src/App.ts.vue'
    at Object.statSync (fs.js:1086:3)
    at isBinaryFileSync (/Users/bakken/.config/yarn/global/node_modules/isbinaryfile/lib/index.js:50:25)
    at renderFile (/Users/bakken/.config/yarn/global/node_modules/@vue/cli/lib/GeneratorAPI.js:478:7)
    at /Users/bakken/.config/yarn/global/node_modules/@vue/cli/lib/GeneratorAPI.js:312:27
    at Generator.resolveFiles (/Users/bakken/.config/yarn/global/node_modules/@vue/cli/lib/Generator.js:268:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Generator.generate (/Users/bakken/.config/yarn/global/node_modules/@vue/cli/lib/Generator.js:175:5)
    at async runGenerator (/Users/bakken/.config/yarn/global/node_modules/@vue/cli/lib/invoke.js:111:3)
    at async invoke (/Users/bakken/.config/yarn/global/node_modules/@vue/cli/lib/invoke.js:92:3)`

**Comment by ElijahKotyluk** [comment]
Typescript and v3 for the CLI is not implemented yet, this is something I’m planning to have ready over the next couple days.

**Comment by cohlar** [comment]
Hi, are there any news on that? 😅 
I was hoping to try out Vuetify 3 alpha with my new TypeScript project
