### ISSUE TITLE
Error thrown whilst using vue-cli-plugin-vuetify v2.2.2

### ISSUE THREAD

**Issue by jb0071913** [vuetifyjs/vue-cli-plugins#253]
Hi

I have just upgraded to use vue-cli-plugin-vuetify v2.2.2 and when I run "vue-cli-service lint --no-fix", I get the following error (I have replaced my project root directory with /path):

> Error resolving webpackConfig TypeError: Cannot read property 'transformAssetUrls' of undefined
    at config.module.rule.use.tap.options (/path/node_modules/vue-cli-plugin-vuetify/index.js:29:44)
    at Object.tap (/path/node_modules/webpack-chain/src/Use.js:14:20)
    at api.chainWebpack.config (/path/node_modules/vue-cli-plugin-vuetify/index.js:28:8)
    at webpackChainFns.forEach.fn (/path/node_modules/@vue/cli-service/lib/Service.js:236:40)

The issue is, on line 29 of vue-cli-plugin-vuetify/index.js, the options parameter is assumed to be defined.

Note, if I revert to version 2.0.9 of the plugin, there are no errors thrown.

**Comment by ElijahKotyluk** [comment]
Try upgrading to version `"2.4.1"`, and let me know if that settles it for you.

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
