### ISSUE TITLE
v2.4.1 prevents vue-cli-plugin-vuetify from installing custom settings

### ISSUE THREAD

**Issue by lartheon** [vuetifyjs/vue-cli-plugins#277]
the latest version causes the following error when install vuetify. If I select the non custom configuration option I am able to install without error.

steps to reproduce (am trying out vue3 with vuetify alpha with typescript)

- install v2.3.1
- run 'vue add vuetify'
- select  'Configure (advanced)'
- select any of the followup options yes or no

```
�  Invoking generator for vue-cli-plugin-vuetify...
 ERROR  Error: You cannot call "get" on a collection with no paths. Instead, check the "length" property first to verify at least 1 path exists.
Error: You cannot call "get" on a collection with no paths. Instead, check the "length" property first to verify at least 1 path exists.
    at Collection.get (X:\xx\User\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\jscodeshift\src\Collection.js:213:13)
    at injectOptions (X:\xx\User\AppData\Roaming\npm\node_modules\@vue\cli\lib\util\codemods\injectOptions.js:15:6)
    at runTransformation (X:\xx\User\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\vue-codemod\dist\src\run-transformation.js:61:17)
    at X:\xx\User\AppData\Roaming\npm\node_modules\@vue\cli\lib\Generator.js:290:23
    at Array.forEach (<anonymous>)
    at Generator.resolveFiles (X:\xx\AppData\Roaming\npm\node_modules\@vue\cli\lib\Generator.js:276:24)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Generator.generate (X:\xx\User\AppData\Roaming\npm\node_modules\@vue\cli\lib\Generator.js:175:5)
    at async runGenerator (X:\xx\User\AppData\Roaming\npm\node_modules\@vue\cli\lib\invoke.js:111:3)
    at async invoke (X:\xx\User\AppData\Roaming\npm\node_modules\@vue\cli\lib\invoke.js:92:3)
```

**Comment by ElijahKotyluk** [comment]
The `Configure (advanced)` option currently doesn't support Vue/Vuetify 3. Some of the options provided in the prompt are not yet supported in the current state of Vuetify 3. 
There could probably be a major version check on Vue which would enable/disable certain prompt questions based on that.

**Comment by lartheon** [comment]
> The `Configure (advanced)` option currently doesn't support Vue/Vuetify 3. Some of the options provided in the prompt are not yet supported in the current state of Vuetify 3.
> There could probably be a major version check on Vue which would enable/disable certain prompt questions based on that.

ok thanks
