### ISSUE TITLE
Error resolving webpackConfig TypeError: Cannot read properties of undefined (reading 'vuetify')

### ISSUE THREAD

**Issue by Juknum** [vuetifyjs/vue-cli-plugins#323]
The following error happened when we tried to install vuetify using `vue add vuetify` :
```log
Error resolving webpackConfig TypeError: Cannot read properties of undefined (reading 'vuetify')
    at E:\GitHub\AE\sith\node_modules\vue-cli-plugin-vuetify\index.js:24:60
    at E:\GitHub\AE\sith\node_modules\@vue\cli-service\lib\Service.js:268:40
    at Array.forEach (<anonymous>)
    at Service.resolveChainableWebpackConfig (E:\GitHub\AE\sith\node_modules\@vue\cli-service\lib\Service.js:268:26)
    at Service.resolveWebpackConfig (E:\GitHub\AE\sith\node_modules\@vue\cli-service\lib\Service.js:272:48)
    at Object.<anonymous> (E:\GitHub\AE\sith\node_modules\@vue\cli-service\webpack.config.js:12:26)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
```
We followed instructions from the [official doc](https://next.vuetifyjs.com/en/getting-started/installation/) and selected the `Vuetify 3 Preview (Vuetify 3)` preset; we didn't allow nightly build as we only want to be on the latest "stable" version of Vuetify.
Then the script started and we got spammed with the error above;

## Additional info: 
> We installed Vue 3 using the CLI and those options below:  

![image](https://user-images.githubusercontent.com/49886317/167491681-6fec3fe3-ca0b-4124-811f-1a2038c129c0.png)
Is there anything we are doing wrong? 
> You can access the full repo [here](https://github.com/ae-utbm/sith4/tree/repo-init) (without Vuetify since it's not working properly)

**Comment by Juknum** [comment]
This issue has been mysteriously solved by itself (we may have changed files location/directories setup);
I'm closing it
